#!/bin/bash
set -e

echo "**********************************"
echo "*** jCrApi2 Post Commit Hook ***"
echo "**********************************"

java --version

echo "get staged files..."
filesToFormat="$(git --no-pager diff --name-status --no-color --staged | awk '$1 != "D" && $2 ~ /\.kts|\.java|\.kt/ { print $NF}')"

echo "re-add files to stage $filesToFormat"

for sourceFilePath in $filesToFormat
do
  echo "re-add to stage $sourceFilePath"
  git add "$sourceFilePath"
done;

echo "*** FINISHED ***"